name: syncfusion_flutter_pdf
description: The Flutter PDF is a library written natively in Dart for creating, reading, editing, and securing PDF files in Android, iOS, and web platforms.
version: 22.2.10
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_pdf

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  xml: ">=5.1.0 <7.0.0"
  syncfusion_flutter_core: ^22.2.10     
  crypto: ">=3.0.0 <4.0.0"
  convert: ">=3.0.0 <4.0.0"

